version: "3.9"

services:
  bio-lib-web:
    image: biocad-library/web:0.0.1
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - bio-lib-srv
    networks:
      bio-net:

  bio-lib-srv:
    image: biocad-library/service:0.0.1
    build:
      context: ./backend
      dockerfile: ./Interview.Biocad.Library/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - Biocad_Library__Books__Path=books.json
      - ASPNET__Logging__LogLevel__Default=Debug
      - ASPNET__Logging__LogLevel__Microsoft.AspNetCore=Debug
    networks:
      bio-net:

networks:
  bio-net:
